{% set version = "1.3.2" %}

package:
  name: proteus
  version: {{ version }}

source:
  fn: proteus-{{ version }}.tar.gz
  url: https://github.com/erdc-cm/proteus/archive/{{ version }}.tar.gz
  sha256: 7592b5175773a723d1c547b3dd1dc2be5f16a0b84c44a3cf3699271b4ba8dc06
  patches:
    - use-member-initializer-list.patch
    - Fix-comparision-with-None.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cython >=0.24
    - daetk
    - hdf5 1.8.*
    - metis 5.*
    - mpich 3.*
    - openblas 0.2.*
    - parmetis 4.0.*
    - petsc4py 3.7.*
    - petsc 3.7.*
    - python
    - scorec
    - superlu 5.*
    - superlu_dist 4.*
    - triangle 1.6*

  run:
    - cython >=0.24
    - daetk
    - hdf5 1.8.*
    - matplotlib
    - metis 5.*
    - mpich 3.*
    - mpi4py 2.*
    - nose
    - openblas 0.2.*
    - parmetis 4.0.*
    - petsc4py 3.7.*
    - petsc 3.7.*
    - pytables 3.2.*
    - pytest
    - pytest-xdist
    - python
    - scipy 0.19.*
    - scorec
    - tetgen

tests:
  imports:
    - proteus

about:
  home: http://proteustoolkit.org
  summary: Proteus is a Python package for rapidly developing computer models and numerical methods.
  dev_url: https://github.com/erdc-cm/proteus
